name = "edgepdf"
main = "src/worker.ts"
compatibility_date = "2024-03-01"

# Custom domain configuration
routes = [
  { pattern = "pdf.andog.eu", custom_domain = true }
]

[assets]
directory = "dist"

# R2 Bucket Binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "edge-pdf-save"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "edge-pdf-db"
database_id = "cbfde966-6a4f-42ef-80c1-f459224847da"
